{
 "title": "nopCommerce - Log Volume & Level Distribution",
 "tags": [
  "nopCommerce",
  "logs",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "level",
    "query": ".*, ERROR, WARN, INFO, ERROR|WARN"
   },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Total Info Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"nopcommerce-service\"} |~ \"(?i)INFO\" |~ \"(?i)${search}\" [1m]))",
     "legendFormat": "INFO"
    }
   ]
  },
  {
   "title": "Total Warn Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"nopcommerce-service\"} |~ \"(?i)WARN\" |~ \"(?i)${search}\" [1m]))",
     "legendFormat": "WARN"
    }
   ]
  },
  {
   "title": "Total Error Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"nopcommerce-service\"} |~ \"(?i)ERROR\" |~ \"(?i)${search}\" [1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "Log Level Distribution Over Time (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"nopcommerce-service\"} |~ \"(?i)INFO\" |~ \"(?i)${search}\" [1m])) by (level)",
     "legendFormat": "INFO"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"nopcommerce-service\"} |~ \"(?i)WARN\" |~ \"(?i)${search}\" [1m])) by (level)",
     "legendFormat": "WARN"
    },
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"nopcommerce-service\"} |~ \"(?i)ERROR\" |~ \"(?i)${search}\" [1m])) by (level)",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "Logs (Loki)",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"nopcommerce-service\"} |~ \"(?i)${search}\" |~ \"(?i)${level}\""
    }
   ]
  }
 ]
}